#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : colcon-devtools
Version  : 0.2.1
Release  : 1
URL      : https://files.pythonhosted.org/packages/1d/ac/8f67927a04e8c05fb9d7abca0f5954382e92d136e00c9d961a8875b84bd7/colcon-devtools-0.2.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/1d/ac/8f67927a04e8c05fb9d7abca0f5954382e92d136e00c9d961a8875b84bd7/colcon-devtools-0.2.1.tar.gz
Summary  : Extension for colcon to provide information about all extension points and extensions
Group    : Development/Tools
License  : Apache-2.0
Requires: colcon-devtools-python3
Requires: colcon-devtools-python
BuildRequires : buildreq-distutils3

%description
===============

%package python
Summary: python components for the colcon-devtools package.
Group: Default
Requires: colcon-devtools-python3

%description python
python components for the colcon-devtools package.


%package python3
Summary: python3 components for the colcon-devtools package.
Group: Default
Requires: python3-core

%description python3
python3 components for the colcon-devtools package.


%prep
%setup -q -n colcon-devtools-0.2.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1532980561
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
